apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: docker.io/library/backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      NodePort: 30007
  type: NodePort
